In [17]:
# import numpy
import numpy as np


In [18]:
def find_ones_with_dp(data):
    """ Data is a 2D array. Find the length of longest consecutive 1s and corresponding index.
        Use Dynamical Programming to speed the function.
    Args:
        data (np.array): 2D np.array
    """
    # create a 2D array to store the length of consecutive 1s
    dp = np.zeros(data.shape, dtype=int)
    # initialize the first row
    dp[0, :] = data[0, :]
    dp[:, 0] = data[:, 0]

    for i in range(1, data.shape[0]):
        for j in range(1, data.shape[1]):
            if data[i, j] == 1:
                dp[i, j] = max(dp[i-1, j], dp[i, j-1]) + 1
    # find the max length
    max_length = np.max(dp)
    # find the index of max length
    max_index = np.where(dp == max_length)

    return max_length, max_index


In [21]:
arr = np.random.randint(0, 2, (5, 5))
print(arr)

print(find_ones_with_dp(arr))
print(find_ones_by_loop(arr))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 0 1 1]
 [0 1 1 1 1]
 [1 1 0 0 1]]
(5, (array([4], dtype=int64), array([4], dtype=int64)))
(3, [(0, 2)])
